print ("Please enter your name: ")
name = input()
print ("please enter your age")
age = input()
print ("Hello "+name+" how are you?")
print ("I am "+age+ " years old.")
#print ("father name:asad ali")
#print ("nationality:Pakistani")
#print ("marital status : unmarried")
#print("Intorduction: A DEDICATED TEAM PLAYER WITH PROFESSIONAL ABILITIES,PRODUCTIVE IDEAS,OUT OF THE BOX THINKER, AND RESPONSIBLE POSITION IN A PROFESSIONAL ORGANIZATION WHICH PR")