print ("PLease enter your name:")
name = input()
print ("Please enter your age: ")
age= input()
print ("Please enter your nationality: ")
nationality = input()
print ("Please enter your gender:")
gender = input()
print ("please enter marital status: ")
maritalStatus = input()

print ("------CV------")
print ("name:"+name)
print ("age:"+age)
print("Nationality:"+nationality )
print ("gender: "+gender)
print ("marital Status:"+maritalStatus)
print("---------------")