print("STAR")

print("         *")
print("        * *")
print("       * * *")
print("      * * * *")
print("     * * * * *")
print("      * * * *")
print("       * * *")
print("        * *")
print("         *")
